# Generated by Django 5.1.7 on 2025-05-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_shoe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='size',
            field=models.CharField(default='42', max_length=5),
        ),
    ]
