# Generated by Django 5.1.7 on 2025-05-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_cartitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(default='42', max_length=5),
        ),
    ]
