# Generated by Django 5.1.7 on 2025-05-20 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_orderitem_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
